#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#  Pre push file - for Itransition2020
#
#  Needed to avoid bugs getting into
#master and Development branches.
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
name: Itransition2020

on:
  push:
    branches:
      - master
      - Development
  pull_request:
    branches:
      - master
      - Development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B verify -f pom.xml
